name: 'Podman login'
description: 'GitHub Action to login against a container registry'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
  logout:
    description: 'Set to true if you want to logout once the workflows completes'
    required: false
    default: 'false'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
